# Permalinks
permalink:           pretty

# Setup
title:               shreyak vashisht
tagline:             A Moderately Okay Data Science Blog
url:                https://shreyak9.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              shreyak vashisht 
  linkedin_url:      https://www.linkedin.com/in/shreyak-vashisht/         
  email:             svashisht2018@student.hult.edu

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/shreyak9

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
